source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '7.2.0'
  pod 'UIPilot', '~> 2.0.2'
end
